project:
  type: website

website:
  title: "Crab Water"
  description: "This is a nonsensical personal blog by Adam Kemberling. Your trusted source for R & python hacks relating to marine science research."
  navbar:
    right:
      - text: Blog
      - href: blog.qmd
      - icon: github
        href: https://github.com/adamkemberling
      - icon: twitter
        href: https://twitter.com/KemberlingAdam
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

